# config file

metadata:
  schema_version: 0.1example
  id: ExampleConfig

data:
  Name: Marcel
  City: Walnut Creek
  Id: 123
  State: CA
  Options:
    - foo
    - baz
  Rabbitmq:
    main:
      host: localhost
      user: guest
      password: guest
    secondary:
      host: localhost2
      user: willem
      password: waters
      vhost: /dev
      weirdfield: ellenven
  MySql:
    host: localhost
  Redis:
    - host: localhost
      db: 0
    - host: localhost2
      db: 1
  MyArray:
    - path: ./path1
    - path: ./path2
    - path: ./path3
