# config file

metadata:
  schema_version: 0.1example
  id: ExampleConfig

data:
  Name: Marcel
  City: Walnut Creek
  Id: 12345
  Options:
    - Foo
    - Bar
  Rabbitmq:
    map:
      main:
        host: localhost
        user: guest
        password: guest
      secondary:
        host: localhost2
        user: willem
        password: waters
  MySql:
    host: localhost
  Redis:
    array:
      - host: localhost
        db: 0
      - host: localhost2
        db: 1
  MyArray:
    - path: ./path1
    - path: ./path2
    - path: ./path3
